# define some variables
variables:
stages:
    - compile_diagrams

# compile pdf
compile_pdf:
    stage: compile_diagrams

    image: tianon/latex

    script:
        make
    artifacts:
        paths:
            - thesis.pdf
            - particles.pdf
            - tauJetCartoon.pdf
            - proton.pdf
        expire_in: 1 week
