# define some variables
variables:
stages:
    - compile_diagrams

# compile pdf
compile_pdf:
    stage: compile_diagrams

    image: tianon/latex

    script:
        make
    artifacts:
        paths:
            - make_proton.pdf
            - make_particles.pdf
            - make_tauJetCartoon.pdf
        expire_in: 1 week
