# define some variables
variables:
stages:
    - compile_diagrams

# compile pdf
compile_pdf:
    stage: compile_diagrams

    image: tianon/latex

    script:
        pdflatex -shell-escape SumCosDPhi.tex
        pdflatex -shell-escape particles.tex
        pdflatex -shell-escape tauJetCartoon.tex
        pdflatex -shell-escape proton.tex
    artifacts:
        paths:
            - thesis.pdf
            - SumCosDPhi.pdf
            - particles.pdf
            - tauJetCartoon.pdf
            - proton.pdf
        expire_in: 1 week
